version: 0.0
os: linux
files:
  - source: /phpinfo.php
    destination: /usr/share/nginx/html/
permissions:
  - object: /usr/share/nginx/html/
    owner: root
    group: root
hooks:
BeforeInstall:
        - location: Scripts/beforeInstall.bash
AfterInstall:
        - location: Scripts/afterInstall.bash
